---
- name: Playbook to manage IPA role member.
  hosts: ipaserver
  become: yes
  gather_facts: no

  tasks:
  - name: Ensure role member 'service' is absent.
    iparole:
      ipaadmin_password: SomeADMINpassword
      name: testrole
      service:
      - http/www.example.com
      action: member
      state: absent
