---
- name: Host member managedby_host absent
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure host member managedby_host 'server.example.com' is absent
    ipahost:
      ipaadmin_password: SomeADMINpassword
      name: host01.example.com
      managedby_host: server.example.com
      action: member
      state: absent
