---
- name: Hosts member principal present
  hosts: ipaserver
  become: true

  tasks:
  - name: Hosts host01.exmaple.com and host02.exmaple.com member principals host/testhost0X.exmaple.com present
    ipahost:
      ipaadmin_password: SomeADMINpassword
      hosts:
      - name: host01.exmaple.com
        principal:
        - host/testhost01.exmaple.com
      - name: host02.exmaple.com
        principal:
        - host/testhost02.exmaple.com
      action: member
