---
- name: Host member principal absent
  hosts: ipaserver
  become: true

  tasks:
  - name: Host host01.example.com principals host/testhost01.example.com and host/myhost01.example.com absent
    ipahost:
      ipaadmin_password: SomeADMINpassword
      name: host01.example.com
      principal:
      - host/testhost01.example.com
      - host/myhost01.example.com
      action: member
      state: absent
