---
- name: Hosts member managedby_host absent
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure hosts manadegby_host is absent.
    ipahost:
      ipaadmin_password: SomeADMINpassword
      hosts:
      - name: host01.exmaple.com
        managedby_host: server.exmaple.com
      - name: host02.exmaple.com
        managedby_host: server.exmaple.com
      action: member
      state: absent
