---
- name: Hosts member principal present
  hosts: ipaserver
  become: true

  tasks:
  - name: Hosts host01.example.com and host02.example.com member principals host/testhost0X.example.com present
    ipahost:
      ipaadmin_password: SomeADMINpassword
      hosts:
      - name: host01.example.com
        principal:
        - host/testhost01.example.com
      - name: host02.example.com
        principal:
        - host/testhost02.example.com
      action: member
