---
- name: Playbook to manage DNS forward zone
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure DNS forward zone is present
    ipadnsforwardzone:
      ipaadmin_password: SomeADMINpassword
      name: example.com
      forwarders:
        - ip_address: 8.8.8.8
      forwardpolicy: first
      skip_overlap_check: true
      permission: yes
