---
- name: Playbook to manage DNS forward zone
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure DNS forward zone is present with forwarder address and non-standard port.
    ipadnsforwardzone:
      ipaadmin_password: SomeADMINpassword
      name: example.com
      forwarders:
        - ip_address: 192.168.100.123
          port: 8063
