---
- name: Playbook to manage DNS forward zone
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure DNS forward zone is absent
    ipadnsforwardzone:
      ipaadmin_password: SomeADMINpassword
      state: absent
