---
- name: Sysaccount example
  hosts: ipaserver
  become: false

  tasks:
  - name: Ensure sysaccount my-app is not privileged
    ipasysaccount:
      ipaadmin_password: SomeADMINpassword
      name: my-app
      privileged: false
