---
- name: Permission Allow Read Employee Number Example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission is present with set of rights to attribute employeenumber
    ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: TestPerm1
      object_type: user
      right:
        - read
        - search
        - compare
      attrs: employeenumber
