---
- name: Selfservice present
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure selfservice "basic manager attributes" is present
    ipaselfservice:
      ipaadmin_password: SomeADMINpassword
      name: "basic manager attributes"
      permission: read
      attribute:
      - businesscategory
