---
- name: Selfservice member absent
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure selfservice "basic manager attributes" member attributes businesscategory and departmentnumber are absent
    ipaselfservice:
      ipaadmin_password: SomeADMINpassword
      name: "basic manager attributes"
      attribute:
      - businesscategory
      - departmentnumber
      action: member
      state: absent
