---
- name: Playbook to manage sudo command
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure sudo command is present
    ipasudocmd:
      ipaadmin_password: SomeADMINpassword
      name: /usr/bin/su
      state: present
