---
- name: Automember orphan group rules are removed example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure orphan group rules are removed
    ipaautomember:
      ipaadmin_password: SomeADMINpassword
      automember_type: group
      state: orphans_removed
