---
- name: Playbook to manage IPA service.
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure service is present
    ipaservice:
      ipaadmin_password: SomeADMINpassword
      name: HTTP/www.ansible.com
      skip_host_check: yes
