---
- name: Playbook to disable IPA service.
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure service is disabled
    ipaservice:
      ipaadmin_password: SomeADMINpassword
      name: HTTP/www.example.com
      state: disabled
