---
- name: Location present test
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure location my_location1 is present
    ipalocation:
      ipaadmin_password: SomeADMINpassword
      name: my_location1
