---
- name: Location absent test
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure location my_location1 is absent
    ipalocation:
      ipaadmin_password: SomeADMINpassword
      name: my_location1
      state: absent
