---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure sudorule is present with the given order.
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      order: 2
