---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure sudorule 'runasuser' member 'admin' is absent.
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      runasuser: admin
      action: member
      state: absent
