---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure sudorule members are absent.
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      allow_sudocmd:
      - /sbin/ifconfig
      deny_sudocmd:
      - /usr/bin/vim
      allow_sudocmdgroup:
      - devops
      deny_sudocmdgroup:
      - users
      action: member
      state: absent
