---
- name: Tests
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure sudorule command is present
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      description: A test sudo rule.
      allow_sudocmd: /bin/ls
      deny_sudocmd: /bin/vim
      state: present
