---
- name: Playbook to manage sudorule
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
  - name: Ensure hostmask network is present in sudorule
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      hostmask: 192.168.122.37/24
      action: member
