---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure hostgroup 'cluster' is present in sudorule
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      hostgroup: cluster
      action: member
