---
- name: Idview host member applied example
  hosts: ipaserver
  become: no

  tasks:
  - name: Ensure host testhost.example.com is applied to idview test_idview
    ipaidview:
      ipaadmin_password: SomeADMINpassword
      name: test_idview
      host: testhost.example.com
      action: member
