---
- name: Netgroup absent example
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
  - name: Ensure netgroup my_netgroup1 is absent
    ipanetgroup:
      ipaadmin_password: SomeADMINpassword
      name: my_netgroup1
      state: absent
