---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure HBAC Services for http and tftp are absent
    ipahbacsvc:
      ipaadmin_password: SomeADMINpassword
      name: http,tftp
      state: absent
