---
- name: Playbook to handle hostgroups
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure host-group databases is absent
    ipahostgroup:
      ipaadmin_password: SomeADMINpassword
      name: databases
      state: absent
