---
- name: Playbook to manage DNS records.
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure that 'host04' A and AAAA records are absent.
    ipadnsrecord:
      ipaadmin_password: SomeADMINpassword
      zone_name: ipatest.local
      records:
      - name: host04
        a_ip_address: 192.168.122.104
      - name: host04
        aaaa_ip_address: ::1
      state: absent
