---
- name: Server enabled example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure server "{{ 'ipareplica1.' + ipaserver_domain }}" with location "mylocation"
    ipaserver:
      ipaadmin_password: SomeADMINpassword
      name: "{{ 'ipareplica1.' + ipaserver_domain }}"
      location: "mylocation"
