---
- name: Playbook to handle sudocmdgroups
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure sudocmdgroup is absent
    ipasudocmdgroup:
      ipaadmin_password: pass1234
      name: network
      state: absent
      action: sudocmdgroup
