---
- name: Playbook to handle sudocmdgroups
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure sudocmdgroup sudocmds are present
    ipasudocmdgroup:
      ipaadmin_password: SomeADMINpassword
      name: network
      description: Group of important commands.
      sudocmd:
      - /usr/sbin/ifconfig
      - /usr/sbin/iwlist
      state: present
