---
- name: Servicedelegationtarget absent example
  hosts: ipaserver
  become: no

  tasks:
  - name: Ensure member test/example.com is absent in servicedelegationtarget test-delegation-target
    ipaservicedelegationtarget:
      ipaadmin_password: SomeADMINpassword
      name: test-delegation-target
      principal: test/example.com
      action: member
      state: absent
