---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Archieve data into symmetric vault.
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: symvault
      username: admin
      vault_password: SomeVAULTpassword
      vault_data: The world of Ï€ is half rounded.
      action: member
