---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure vault member "user" is absent.
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: keychain
      username: admin
      state: absent
      action: member
      users:
      - user01
      - user02
