---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure shared vault is present.
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: sharedvault
      shared: True
      ipavaultpassword: MyVaultPassword123
      state: present
