---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - ipavault:
      ipaadmin_password: SomeADMINpassword
      name: keychain
      username: admin
      state: present
      action: member
      users: user1
