- name: Install - Initialize ipaserver_external_cert_files
  set_fact:
     ipaserver_external_cert_files: []
  when: ipaserver_external_cert_files is undefined
- name: Install - Copy "{{ item }}" "{{ inventory_hostname }}':/root/'{{ item | basename }}"
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item | basename }}"
    force: yes
- name: Install - Extend ipaserver_external_cert_files with "/root/{{ item | basename }}"
  set_fact:
    ipaserver_external_cert_files: "{{ ipaserver_external_cert_files }} + [ '/root/{{ item | basename }}' ]"
