- block:
  - name: Verify Python3 import
    script: py3test.py
    register: py3test
    failed_when: False
    changed_when: False

  - name: Set python interpreter to 3
    set_fact:
      ansible_python_interpreter: "/usr/bin/python3"
    when: py3test.rc == 0

  - name: Fail for IPA 4.5.90
    fail: msg="You need to install python2 bindings for ipa server usage"
    when: py3test.rc != 0 and "not usable with python3" in py3test.stdout

  - name: Set python interpreter to 2
    set_fact:
      ansible_python_interpreter: "/usr/bin/python2"
    when: py3test.failed or py3test.rc != 0
