---
name: ansible-test sanity
on:
  - push
  - pull_request
jobs:
  ansible_test:
    name: Verify ansible-test sanity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Run ansible-test
        run: bash tests/sanity/sanity.sh
