---
name: Verify Ansible documentation.
on:
  - push
  - pull_request
jobs:
  check_docs_oldest_supported:
    name: Check Ansible Documentation with ansible-core 2.16.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install Ansible 2.16
        run: |
          python -m pip install "ansible-core >=2.16,<2.17"
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins

  check_docs_previous:
    name: Check Ansible Documentation with ansible-core 2.18.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install Ansible 2.18
        run: |
          python -m pip install "ansible-core >=2.18,<2.19"
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins

  check_docs_current:
    name: Check Ansible Documentation with ansible-core 2.19.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install Ansible 2.20
        run: |
          python -m pip install "ansible-core <2.20"
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins

  check_docs_ansible_latest:
    name: Check Ansible Documentation with latest Ansible version.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install Ansible-latest
        run: |
          python -m pip install ansible
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins
