---
name: Verify Ansible documentation.
on:
  - push
  - pull_request
jobs:
  check_docs_oldest_supported:
    name: Check Ansible Documentation with ansible-core 2.13.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.x'
      - name: Install Ansible 2.13
        run: |
          python -m pip install "ansible-core >=2.13,<2.14"
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins

  check_docs_previous:
    name: Check Ansible Documentation with ansible-core 2.14.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.x'
      - name: Install Ansible 2.14
        run: |
          python -m pip install "ansible-core >=2.14,<2.15"
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins

  check_docs_current:
    name: Check Ansible Documentation with ansible-core 2.15.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.x'
      - name: Install Ansible 2.15
        run: |
          python -m pip install "ansible-core >=2.15,<2.16"
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins

  check_docs_ansible_latest:
    name: Check Ansible Documentation with latest Ansible version.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.x'
      - name: Install Ansible-latest
        run: |
          python -m pip install ansible
      - name: Run ansible-doc-test
        run: |
          ANSIBLE_LIBRARY="." ANSIBLE_DOC_FRAGMENT_PLUGINS="." python utils/ansible-doc-test -v roles plugins
